[package]
name = "poseidon"
version = "0.1.0"
edition = "2021"


[dependencies]
ff = "0.12.0"
hex = "0.4.3"
hex-literal = "0.3.4"
secq256k1 = { path = "../secq256k1" }
getrandom = { version = "0.2.8", features = ["js"] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
typenum = "1.16.0"
neptune = "8.1.0"
blstrs = { version = "0.6.0" }

